apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: prod
  annotations:
    ingress.bluemix.net/client-max-body-size: "512m"
    ingress.bluemix.net/redirect-to-https: "true"
    ingress.bluemix.net/rewrite-path: |
      serviceName=video-analysis rewrite=/;
      serviceName=social-media-annotation-tool rewrite=/;
      serviceName=sensor-things-server rewrite=/;
      serviceName=mobileapp rewrite=/browser/www/;
  name: rules-prod
spec:
  tls:
  - hosts:
    - beaware.uk-south.containers.mybluemix.net
    secretName: beaware
  rules:
  - host: beaware.uk-south.containers.mybluemix.net
    http:
      paths:
        - path: /video-analysis/
          backend:
            serviceName: video-analysis
            servicePort: 7777
        - path: /social-media-annotation-tool/
          backend:
            serviceName: social-media-annotation-tool
            servicePort: 2020
        - path: /sensor-things-server/
          backend:
            serviceName: sensor-things-server
            servicePort: 8080
        - path: /mobileapp/
          backend:
            serviceName: mobileapp
            servicePort: 8000
        - path: /servlet/is/
          backend:
            serviceName: knowledgebase
            servicePort: 80
        - path: /Bitmaps/
          backend:
            serviceName: knowledgebase
            servicePort: 80
        - path: /css/
          backend:
            serviceName: knowledgebase
            servicePort: 80
        - path: /js/
          backend:
            serviceName: knowledgebase
            servicePort: 80
